export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const ACTION_EXAMPLE = 'ACTION_EXAMPLE';
export const ACTION_EXAMPLE_TWO = 'ACTION_EXAMPLE_TWO';
export const ACTION_EXAMPLE_ERROR = 'ACTION_EXAMPLE_ERROR';