apiVersion: v1
kind: Service
metadata:
  name: testreactdeploy
spec:
  selector:
    app: testreactdeploy
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testreactdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testreactdeploy
  template:
    metadata:
      labels:
        app: testreactdeploy
    spec:
      containers:
        - name: testreactdeploy
          image: rahul65422/testreactdeploy:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BASE_URL
              value: http://192.168.49.2:31916/
          imagePullPolicy: Always
